spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

        registration:
          google:
            clientId: 13935910419-05o0sqdsuc6e24c7iq6om9anutusparn.apps.googleusercontent.com
            clientSecret: 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
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: POST
            clientName: Google
            scope:
              - profile
          naver:
            clientId: ksqG6QT6oravThTNRnxT
            clientSecret: sIAb1ykdrp
            redirectUri: http://localhost:8080/login/oauth2/code/naver
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: POST
            clientName: Naver
          kakao:
            clientId: dafe7d29e20a323120b6df9ff92a25d6
            clientSecret: YTSxknLityIxxHnFi1x0Ru8ZCofPQnVs
            redirectUri: http://localhost:8080/login/oauth2/code/kakao
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: POST
            clientName: Kakao

mybatis:
  mapper-locations:
    - /mappers/*.xml

jwt:
  secret: 842bc7c097a91cb88cbea97df0f3367a8254e95f841f30289d58fc7323e46758dfc301ada7d55b4f797aec511f36a75fff32c3d9ef9110004b8fa25bc20cdf62a9f745c05882cd276970b759db2c8281765fd91b7593c292f1ba619bc985c3ee6aab858f70127fba9acbf2793760acd146c96793c245098e221384f976d6bc8372e36c8a7e70505ed2526eb37cd1e2c8545d0d057905b7f0cb8cf0efe27e9d499dd95733a9277b0d8adef44f75a40204c469dfc877458dbeccf53909fea5ea394bdc5e2a47cd164ff3e18cc49de76237f3cd9951b92e0f40b0d1d828f545b4d5bad7f1bba35576df93eda19e170a75dcc4ea34e6310848150312cd8031855160